name: Erlang CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp:
          - "24.2.1.0"
          - "23.3.4.11"
          - "22.3.4.24"

    container:
      image: erlang:${{ matrix.otp }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: ./rebar3 compile
      - name: Run eunit
        run: ./rebar3 as gha do eunit --module=riak_repl2_rt_source_sink_tests
